# ── Summon / Familiar Templates ─────────────────────────────────────────

SUMMON_TEMPLATES: dict[str, dict] = {
    # ── Find Familiar forms (PHB p.240) ──
    "familiar_bat": {
        "name": "Bat", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 12, "hp_max": 1, "speed": "5 ft., fly 30 ft.",
        "stats": {"str":2,"dex":15,"con":8,"int":2,"wis":12,"cha":4},
        "senses": "blindsight 60 ft., passive Perception 11",
        "features": ["Echolocation","Keen Hearing"],
        "attacks": [{"name":"Bite","bonus":0,"damage":"1 piercing"}],
    },
    "familiar_cat": {
        "name": "Cat", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 12, "hp_max": 2, "speed": "40 ft., climb 30 ft.",
        "stats": {"str":3,"dex":15,"con":10,"int":3,"wis":12,"cha":7},
        "skills": "Perception +3, Stealth +4",
        "senses": "passive Perception 13",
        "features": ["Keen Smell"],
        "attacks": [{"name":"Claws","bonus":0,"damage":"1 slashing"}],
    },
    "familiar_hawk": {
        "name": "Hawk", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 13, "hp_max": 1, "speed": "10 ft., fly 60 ft.",
        "stats": {"str":5,"dex":16,"con":8,"int":2,"wis":14,"cha":6},
        "skills": "Perception +4",
        "senses": "passive Perception 14",
        "features": ["Keen Sight"],
        "attacks": [{"name":"Talons","bonus":5,"damage":"1 slashing"}],
    },
    "familiar_owl": {
        "name": "Owl", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 11, "hp_max": 1, "speed": "5 ft., fly 60 ft.",
        "stats": {"str":3,"dex":13,"con":8,"int":2,"wis":12,"cha":7},
        "skills": "Perception +3, Stealth +3",
        "senses": "darkvision 120 ft., passive Perception 13",
        "features": ["Flyby","Keen Hearing and Sight"],
        "attacks": [{"name":"Talons","bonus":3,"damage":"1 slashing"}],
    },
    "familiar_rat": {
        "name": "Rat", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 10, "hp_max": 1, "speed": "20 ft.",
        "stats": {"str":2,"dex":11,"con":9,"int":2,"wis":10,"cha":4},
        "senses": "darkvision 30 ft., passive Perception 10",
        "features": ["Keen Smell"],
        "attacks": [{"name":"Bite","bonus":0,"damage":"1 piercing"}],
    },
    "familiar_raven": {
        "name": "Raven", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 12, "hp_max": 1, "speed": "10 ft., fly 50 ft.",
        "stats": {"str":2,"dex":14,"con":8,"int":2,"wis":12,"cha":6},
        "skills": "Perception +3",
        "senses": "passive Perception 13",
        "features": ["Mimicry"],
        "attacks": [{"name":"Beak","bonus":4,"damage":"1 piercing"}],
    },
    "familiar_weasel": {
        "name": "Weasel", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 13, "hp_max": 1, "speed": "30 ft.",
        "stats": {"str":3,"dex":16,"con":8,"int":2,"wis":12,"cha":3},
        "skills": "Perception +3, Stealth +5",
        "senses": "passive Perception 13",
        "features": ["Keen Hearing and Smell"],
        "attacks": [{"name":"Bite","bonus":5,"damage":"1 piercing"}],
    },
    "familiar_spider": {
        "name": "Spider", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 12, "hp_max": 1, "speed": "20 ft., climb 20 ft.",
        "stats": {"str":2,"dex":14,"con":8,"int":1,"wis":10,"cha":2},
        "senses": "darkvision 30 ft., passive Perception 10",
        "features": ["Spider Climb","Web Sense","Web Walker"],
        "attacks": [{"name":"Bite","bonus":4,"damage":"1 piercing + DC 9 Con or 1d4 poison"}],
    },
    "familiar_snake": {
        "name": "Poisonous Snake", "category": "familiar", "source": "find_familiar", "size": "Tiny",
        "ac": 13, "hp_max": 2, "speed": "30 ft., swim 30 ft.",
        "stats": {"str":2,"dex":16,"con":11,"int":1,"wis":10,"cha":3},
        "senses": "blindsight 10 ft., passive Perception 10",
        "features": [],
        "attacks": [{"name":"Bite","bonus":5,"damage":"1 piercing + DC 10 Con or 2d4 poison"}],
    },
    "familiar_octopus": {
        "name": "Octopus", "category": "familiar", "source": "find_familiar", "size": "Small",
        "ac": 12, "hp_max": 3, "speed": "5 ft., swim 30 ft.",
        "stats": {"str":4,"dex":15,"con":11,"int":3,"wis":10,"cha":4},
        "skills": "Perception +2, Stealth +4",
        "senses": "darkvision 30 ft., passive Perception 12",
        "features": ["Hold Breath (30 min)","Underwater Camouflage","Water Breathing","Ink Cloud (1/rest)"],
        "attacks": [{"name":"Tentacles","bonus":4,"damage":"1 bludgeoning, grappled (escape DC 10)"}],
    },

    # ── Pact of the Chain special familiars (PHB p.107) ──
    "chain_imp": {
        "name": "Imp", "category": "pact_chain", "source": "pact_of_the_chain", "size": "Tiny",
        "ac": 13, "hp_max": 10, "speed": "20 ft., fly 40 ft.",
        "stats": {"str":6,"dex":17,"con":13,"int":11,"wis":12,"cha":14},
        "skills": "Deception +4, Insight +3, Persuasion +4, Stealth +5",
        "senses": "darkvision 120 ft., passive Perception 11",
        "features": ["Shapechanger (rat/raven/spider)","Devil's Sight","Magic Resistance"],
        "attacks": [{"name":"Sting","bonus":5,"damage":"1d4+3 piercing + 3d6 poison (DC 11 Con half)"}],
        "hp_note": "Immune: fire, poison. Resist: cold, nonmagical non-silver B/P/S",
    },
    "chain_pseudodragon": {
        "name": "Pseudodragon", "category": "pact_chain", "source": "pact_of_the_chain", "size": "Tiny",
        "ac": 13, "hp_max": 7, "speed": "15 ft., fly 60 ft.",
        "stats": {"str":6,"dex":15,"con":13,"int":10,"wis":12,"cha":10},
        "skills": "Perception +3, Stealth +4",
        "senses": "blindsight 10 ft., darkvision 60 ft., passive Perception 13",
        "features": ["Keen Senses","Magic Resistance","Limited Telepathy (100 ft)"],
        "attacks": [
            {"name":"Bite","bonus":4,"damage":"1d4+2 piercing"},
            {"name":"Sting","bonus":4,"damage":"1d4+2 piercing + poison (DC 11 Con; fail by 5+ = unconscious 1 hr)"},
        ],
    },
    "chain_quasit": {
        "name": "Quasit", "category": "pact_chain", "source": "pact_of_the_chain", "size": "Tiny",
        "ac": 13, "hp_max": 7, "speed": "40 ft.",
        "stats": {"str":5,"dex":17,"con":10,"int":7,"wis":10,"cha":10},
        "skills": "Stealth +5",
        "senses": "darkvision 120 ft., passive Perception 10",
        "features": ["Shapechanger (bat/centipede/toad)","Magic Resistance","Scare (1/day)","Invisibility"],
        "attacks": [{"name":"Claws","bonus":4,"damage":"1d4+3 slashing + 2d4 poison (DC 10 Con half)"}],
        "hp_note": "Immune: poison. Resist: cold/fire/lightning, nonmagical B/P/S",
    },
    "chain_sprite": {
        "name": "Sprite", "category": "pact_chain", "source": "pact_of_the_chain", "size": "Tiny",
        "ac": 15, "hp_max": 2, "speed": "10 ft., fly 40 ft.",
        "stats": {"str":3,"dex":18,"con":10,"int":14,"wis":13,"cha":11},
        "skills": "Perception +3, Stealth +8",
        "senses": "passive Perception 13",
        "features": ["Heart Sight (touch: detect alignment + emotions)","Invisibility"],
        "attacks": [{"name":"Shortbow (80/320)","bonus":6,"damage":"1 piercing + poison (DC 10 Con; fail by 5+ = unconscious 1 min)"}],
    },

    # ── Tasha's Summon Spells (DTCOE) ──
    "tashas_beast": {
        "name": "Summon Beast", "category": "tashas_summon", "source": "summon_beast", "size": "Small",
        "ac": 11, "hp_max": 30, "speed": "30 ft.",
        "stats": {"str":18,"dex":11,"con":16,"int":4,"wis":14,"cha":5},
        "senses": "darkvision 60 ft., passive Perception 12",
        "features": ["Bestial Spirit (air/land/water form)","Pack Tactics (if land)","Flyby (if air)","Amphibious + swim 30 ft (if water)"],
        "attacks": [{"name":"Maul","bonus":6,"damage":"1d8+6 piercing"}],
        "hp_note": "30 + 5/spell level above 2nd",
    },
    "tashas_undead": {
        "name": "Summon Undead", "category": "tashas_summon", "source": "summon_undead", "size": "Medium",
        "ac": 11, "hp_max": 30, "speed": "30 ft., fly 30 ft. (hover — ghostly only)",
        "stats": {"str":14,"dex":8,"con":15,"int":6,"wis":10,"cha":5},
        "senses": "darkvision 60 ft., passive Perception 10",
        "features": ["Ghostly / Putrid / Skeletal form","Festering Aura (putrid)","Grave Bolt (skeletal, ranged 150 ft)"],
        "attacks": [{"name":"Deathly Touch","bonus":5,"damage":"1d8+5 necrotic"}],
        "hp_note": "30 + 10/spell level above 3rd",
    },
    "tashas_fey": {
        "name": "Summon Fey", "category": "tashas_summon", "source": "summon_fey", "size": "Small",
        "ac": 14, "hp_max": 30, "speed": "30 ft., fly 30 ft. (tricksy only)",
        "stats": {"str":8,"dex":18,"con":14,"int":14,"wis":14,"cha":16},
        "senses": "darkvision 60 ft., passive Perception 12",
        "features": ["Fuming / Mirthful / Tricksy mood","Fey Step (bonus action teleport 30 ft)"],
        "attacks": [{"name":"Gleaming Blade","bonus":6,"damage":"1d10+6 force"}],
        "hp_note": "30 + 10/spell level above 3rd",
    },
    "tashas_shadowspawn": {
        "name": "Summon Shadowspawn", "category": "tashas_summon", "source": "summon_shadowspawn", "size": "Medium",
        "ac": 14, "hp_max": 35, "speed": "40 ft.",
        "stats": {"str":13,"dex":16,"con":16,"int":4,"wis":10,"cha":16},
        "senses": "darkvision 120 ft., passive Perception 10",
        "features": ["Fury / Despair / Fear form","Dreadful Scream (fear form, 30 ft AoE)"],
        "attacks": [{"name":"Chilling Rend","bonus":6,"damage":"1d12+6 cold"}],
        "hp_note": "35 + 15/spell level above 3rd",
    },
    "tashas_aberration": {
        "name": "Summon Aberration", "category": "tashas_summon", "source": "summon_aberration", "size": "Medium",
        "ac": 14, "hp_max": 40, "speed": "30 ft., fly 30 ft. (hover — beholderkin only)",
        "stats": {"str":14,"dex":14,"con":16,"int":16,"wis":6,"cha":4},
        "senses": "darkvision 120 ft., passive Perception 8",
        "features": ["Beholderkin / Slaad / Star Spawn form","Regeneration 5 (star spawn)"],
        "attacks": [{"name":"Multiattack (2 claws)","bonus":5,"damage":"1d8+5 slashing per hit"}],
        "hp_note": "40 + 10/spell level above 4th",
    },

    # ── Tasha's Summon Fiend variants (6th level, warlock/wizard) ──
    "tashas_fiend_devil": {
        "name": "Summon Fiend (Devil)", "category": "tashas_summon", "source": "summon_fiend", "size": "Large",
        "ac": 18, "hp_max": 40, "speed": "40 ft., fly 60 ft.",
        "stats": {"str":13,"dex":16,"con":15,"int":10,"wis":10,"cha":16},
        "senses": "darkvision 60 ft., Devil's Sight 120 ft., passive Perception 10",
        "features": ["Devil's Sight (see through magical darkness)","Magic Resistance"],
        "attacks": [{"name":"Hurl Flame (ranged 150 ft)","bonus":9,"damage":"2d6+9 fire"}],
        "hp_note": "40 + 15/spell level above 6th",
    },
    "tashas_fiend_demon": {
        "name": "Summon Fiend (Demon)", "category": "tashas_summon", "source": "summon_fiend", "size": "Large",
        "ac": 18, "hp_max": 50, "speed": "40 ft., climb 40 ft.",
        "stats": {"str":13,"dex":16,"con":15,"int":10,"wis":10,"cha":16},
        "senses": "darkvision 60 ft., passive Perception 10",
        "features": ["Death Throes (2d10+6 fire AoE on death)","Magic Resistance"],
        "attacks": [{"name":"Bite","bonus":9,"damage":"1d12+9 necrotic"}],
        "hp_note": "50 + 15/spell level above 6th",
    },
    "tashas_fiend_yugoloth": {
        "name": "Summon Fiend (Yugoloth)", "category": "tashas_summon", "source": "summon_fiend", "size": "Large",
        "ac": 18, "hp_max": 60, "speed": "40 ft., climb 40 ft.",
        "stats": {"str":13,"dex":16,"con":15,"int":10,"wis":10,"cha":16},
        "senses": "darkvision 60 ft., passive Perception 10",
        "features": ["Teleport 30 ft after claw attack","Magic Resistance"],
        "attacks": [{"name":"Claws + Teleport","bonus":9,"damage":"1d8+9 slashing + teleport 30 ft"}],
        "hp_note": "60 + 15/spell level above 6th",
    },

    # ── Class Summons ──
    "wildfire_spirit": {
        "name": "Wildfire Spirit", "category": "class_feature", "source": "Circle of Wildfire", "size": "Small",
        "ac": 13, "hp_max": 15, "speed": "30 ft., fly 30 ft. (hover)",
        "stats": {"str":10,"dex":14,"con":14,"int":13,"wis":15,"cha":11},
        "senses": "darkvision 60 ft., passive Perception 12",
        "features": ["Flame Seed (ranged spell attack, 60 ft, 1d6+PB fire)","Fiery Teleportation (15 ft AoE teleport + 1d6+PB fire on arrival)"],
        "attacks": [{"name":"Flame Seed","bonus":5,"damage":"1d6+2 fire (60 ft)"}],
        "hp_note": "5 + 5×druid level",
    },
    "steel_defender": {
        "name": "Steel Defender", "category": "class_feature", "source": "Battle Smith", "size": "Medium",
        "ac": 15, "hp_max": 20, "speed": "40 ft.",
        "stats": {"str":14,"dex":12,"con":14,"int":4,"wis":10,"cha":6},
        "skills": "Perception +4",
        "senses": "darkvision 60 ft., passive Perception 14",
        "features": ["Deflect Attack (reaction, impose disadvantage)","Repair (3/day, 2d8+PB)","Vigilant"],
        "attacks": [{"name":"Bite","bonus":4,"damage":"1d8+2 piercing"}],
        "hp_note": "2 + Int mod + 5×artificer level",
    },
}
