"""Thumbnails must be encoded once, not once per request.

Measured before this change: serving a portrait file took 8ms, serving it at `?size=56` took 47ms —
every time, on every request, because the route re-encoded the WebP inline. A page with 60 entity
tiles therefore spent ~3s of CPU per load, inside an `async` route, which stalls every other request
the server is handling. These lock in the two caches and the routing that feeds them.
"""
from __future__ import annotations

import io
import pathlib
import time

from PIL import Image

from services import images

APP = pathlib.Path(__file__).resolve().parent.parent


def _png(path, size=400, colour="red"):
    im = Image.new("RGB", (size, size), colour)
    im.save(path, format="PNG")
    return path


def test_a_file_thumb_is_written_once_and_then_read(tmp_path):
    src = _png(tmp_path / "art.png")

    first = images.cached_thumb(src, 56)
    assert first, "the first call should produce a thumb"
    written = list((tmp_path / "thumbs").glob("*.webp"))
    assert len(written) == 1, "the thumb should be cached next to the source"

    stamp = written[0].stat().st_mtime_ns
    second = images.cached_thumb(src, 56)
    assert second == first
    assert written[0].stat().st_mtime_ns == stamp, "the second call must not rewrite the cache"


def test_new_art_invalidates_the_old_thumb(tmp_path):
    """A portrait is regenerated by rewriting the same path, so the cache is keyed on the source's
    mtime and size rather than on the URL — otherwise the old image would be served forever."""
    src = _png(tmp_path / "art.png", colour="red")
    first = images.cached_thumb(src, 56)
    time.sleep(0.01)
    _png(src, 400, "blue")                       # same path, different bytes
    second = images.cached_thumb(src, 56)
    assert second != first, "new art must not be served the old thumb"
    assert len(list((tmp_path / "thumbs").glob("*.webp"))) == 1, "the stale variant should be gone"


def test_two_sizes_do_not_collide(tmp_path):
    src = _png(tmp_path / "art.png")
    small, big = images.cached_thumb(src, 40), images.cached_thumb(src, 120)
    assert small and big and small != big
    assert len(list((tmp_path / "thumbs").glob("*.webp"))) == 2


def test_blob_thumbs_are_cached_in_memory(monkeypatch):
    blob = io.BytesIO()
    Image.new("RGB", (400, 400), "green").save(blob, format="PNG")
    raw = blob.getvalue()

    calls = {"n": 0}
    real = images.thumbnail_bytes

    def counted(b, size):
        calls["n"] += 1
        return real(b, size)

    monkeypatch.setattr(images, "thumbnail_bytes", counted)
    a = images.thumb_for_blob(raw, 56)
    b = images.thumb_for_blob(raw, 56)
    assert a and a == b
    assert calls["n"] == 1, "the second request for the same bytes and size must not re-encode"


def test_no_route_re_encodes_a_thumbnail_per_request():
    """The regression guard: every image route must go through the cached helpers. A fresh
    `thumbnail_bytes(...)` call inside a route is the bug this whole module exists for."""
    offenders = []
    for rel in ("routes/ref_images.py", "routes/dm.py", "routes/characters/sheet.py"):
        text = (APP / rel).read_text()
        for i, line in enumerate(text.splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("thumb = thumbnail_bytes(") or "= thumbnail_bytes(blob, size)" in line:
                offenders.append(f"{rel}:{i}")
    assert not offenders, f"these re-encode per request: {offenders}"
