"""Global reference tables served as a cached asset instead of inline JSON.

SOURCE_SLUG_MAP (~31 KB) was inlined into /dm-tools, /create and (as dead context) the sheet
page, so every load re-sent byte-identical JSON that the browser and Cloudflare could never
cache — the page's own HTML has no Set-Cookie on it, but the map rode inside that HTML.
It is shared book/rule data with no user rows, which is exactly what may live in a cached
file. NAMED_ITEM_TYPES and SUMMON_TEMPLATES go into the DM library asset instead, because
/dm-tools is their only consumer.

Never put user-owned data here: the DM's characters, encounters, campaigns, custom traps and
DB NPCs stay in the HTML so they can never leak between DMs.
"""

import json

from services.assets import write_static_asset

_ASSET = "source-slug-map.js"
_CREATE_ASSET = "create-consts.js"

#: The /create wizard tests membership on these, so they must arrive as a Set, not an array.
CREATE_SET_CONSTS = ("FLEXIBLE_ASI", "MPMM_ASI")


def ensure_source_slug_map_asset(slug_map) -> str:
    """Write static/source-slug-map.js and return its cache-busting version."""
    body = (
        "/* Generated by services.reference_assets.ensure_source_slug_map_asset().\n"
        "   Global reference data: book/source slug -> {title, ...}. No user rows. */\n"
        "window.SOURCE_SLUG_MAP = "
        + json.dumps(slug_map, separators=(",", ":"), sort_keys=True)
        + ";\n"
    )
    return write_static_asset(_ASSET, body)


def ensure_create_consts_asset(consts: dict) -> str:
    """Write static/create-consts.js and return its cache-busting version.

    `consts` maps the JS name the wizard reads to its global reference value: races, classes,
    skills, backgrounds/alignments and the per-class option/level tables. These were 39 inline
    `const NAME = {{ x | tojson }};` lines in create.html — ~240 KB of JSON re-sent on every
    wizard load and uncacheable, because it rode inside the page's HTML.

    Written as `window.NAME = <json>` so the wizard's existing bare-name reads keep working
    (a window property is reachable as a bare identifier). Names in CREATE_SET_CONSTS are
    emitted wrapped in `new Set(...)`, which is how the template declared them.
    """
    lines = [
        "/* Generated by services.reference_assets.ensure_create_consts_asset().",
        "   Global reference data for the /create wizard: races, classes, skills, backgrounds,",
        "   alignments and the per-class option/level tables. No user rows. */",
    ]
    for name in sorted(consts):
        value = json.dumps(consts[name], separators=(",", ":"), sort_keys=True)
        if name in CREATE_SET_CONSTS:
            value = f"new Set({value})"
        lines.append(f"window.{name} = {value};")
    return write_static_asset(_CREATE_ASSET, "\n".join(lines) + "\n")
