"""Global reference tables served as a cached asset instead of inline JSON.

SOURCE_SLUG_MAP (~31 KB) was inlined into /dm-tools, /create and (as dead context) the sheet
page, so every load re-sent byte-identical JSON that the browser and Cloudflare could never
cache — the page's own HTML has no Set-Cookie on it, but the map rode inside that HTML.
It is shared book/rule data with no user rows, which is exactly what may live in a cached
file. NAMED_ITEM_TYPES and SUMMON_TEMPLATES go into the DM library asset instead, because
/dm-tools is their only consumer.

Never put user-owned data here: the DM's characters, encounters, campaigns, custom traps and
DB NPCs stay in the HTML so they can never leak between DMs.
"""

import json

from services.assets import write_static_asset

_ASSET = "source-slug-map.js"


def ensure_source_slug_map_asset(slug_map) -> str:
    """Write static/source-slug-map.js and return its cache-busting version."""
    body = (
        "/* Generated by services.reference_assets.ensure_source_slug_map_asset().\n"
        "   Global reference data: book/source slug -> {title, ...}. No user rows. */\n"
        "window.SOURCE_SLUG_MAP = "
        + json.dumps(slug_map, separators=(",", ":"), sort_keys=True)
        + ";\n"
    )
    return write_static_asset(_ASSET, body)
